name: abersoft
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3

  # Storage & Data
  shared_preferences: ^2.1.2
  equatable: ^2.0.5

  # Network
  dio: ^5.2.1+1
  alice: ^0.3.3

  # Images
  image_picker: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter

  # Unit Testing
  bloc_test: ^9.1.0
  mockito: ^5.3.2
  mocktail: ^0.3.0

  # Generator
  build_runner:

  # Integration Test
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/